//MISSION-V
//Test bench for RAM password reset module generated on quartus
`timescale 1ps/1ps
module tb_RAM_Password_Reset_Module();
 reg RAM_access1,RAM_access2,password_change,log_out,auth_button;
 reg [3:0] toggle_entry;
 reg [2:0] internal_id;
 reg clock,rst;
 wire [6:0] status;
 wire green_led,red_led,auth_bit;


RAM_Password_Reset_Top_Module RAM_pass1(RAM_access1,RAM_access2,password_change,auth_button,toggle_entry,internal_id,status,log_out,green_led,red_led,auth_bit,clock,rst);
//P1 Generating clock pulses
always
begin
 clock=0;
 #10;
 clock=1;
 #10;
end

//P2 Testing module for different inputs
initial
begin
 rst=0; RAM_access1=0; RAM_access2=1;password_change=1; internal_id=3'b010;
 toggle_entry=4'b0001;
 @(posedge clock);
 #5 rst=1;
 @(posedge clock);
 #5 auth_button=1;
 @(posedge clock);
 #5 auth_button=0;
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 #5 toggle_entry=4'b0010;
 @(posedge clock);
 #5 auth_button=1;
 @(posedge clock);
 #5 auth_button=0;
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 #5 toggle_entry=4'b0011;
 @(posedge clock);
 #5 auth_button=1;
 @(posedge clock);
 #5 auth_button=0;
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 #5 toggle_entry=4'b0100;
 @(posedge clock);
 #5 auth_button=1;
 @(posedge clock);
 #5 auth_button=0;
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 #5 log_out<=1;
 @(posedge clock);
 #5 log_out<=0;
 #5 RAM_access1=1; RAM_access2=0;password_change=0; internal_id=3'b010;
 @(posedge clock);
 toggle_entry=4'b0001;
 @(posedge clock);
 #5 rst=1;
 @(posedge clock);
 #5 auth_button=1;
 @(posedge clock);
 #5 auth_button=0;
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 #5 toggle_entry=4'b0010;
 @(posedge clock);
 #5 auth_button=1;
 @(posedge clock);
 #5 auth_button=0;
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 #5 toggle_entry=4'b0011;
 @(posedge clock);
 #5 auth_button=1;
 @(posedge clock);
 #5 auth_button=0;
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 #5 toggle_entry=4'b0100;
 @(posedge clock);
 #5 auth_button=1;
 @(posedge clock);
 #5 auth_button=0;
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 #5 log_out=1;RAM_access1=0;RAM_access2=0;
 @(posedge clock);
 #5 log_out=0;
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 #5 auth_button=1;
 @(posedge clock);
 #5 auth_button=0;
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 #5 auth_button=1;
 @(posedge clock);
 #5 auth_button=0;
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 #5 auth_button=1;
 @(posedge clock);
 #5 auth_button=0;
 @(posedge clock);
 @(posedge clock);
 @(posedge clock);
 #5 auth_button=1;
 @(posedge clock);
 #5 auth_button=0;
end
endmodule
